spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=${DATABASE_NAME}
    username: ${DATASOURCE_USR}
    password: ${DATASOURCE_PWD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    consul:
      host: localhost
      discovery:
        register: true
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.int[1,999999]}
server:
  port: 0
johans-egen:
  testKey: Hello, world!